# logger options
snapshot_save_iter: 100     # How often do you want to save trained models
log_iter: 100                   # How often do you want to log the training stats

# optimization options
max_iter: 1000             # maximum number of training iterations
num_minibatch: 32768 
batch_size: 8                # batch size
init: xavier                 # initialization [gaussian/kaiming/xavier/orthogonal]
lr: 0.0001                    # initial learning rate
step_size: 1000              # how often to decay learning rate
weight_decay: 0.5            # how much to decay learning rate

# model options
layers: [16, 8, 4]

# data options
input_dims: 16
output_dims: 2